CREATE TABLE EMPLOYEE
(
    ENAME VARCHAR(255) NOT NULL,
    ESSN CHAR(10) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    SALARY INT,
    SUPERSSN CHAR(10),
    DNO VARCHAR(10)
);

CREATE TABLE DEPARTMENT
(
    DNAME VARCHAR(255) NOT NULL,
    DNO VARCHAR(10) PRIMARY KEY,
    MGRSSN CHAR(10),
    MGRSTARTDATE DATE
);

CREATE TABLE PROJECT
(
    PNAME VARCHAR(255) NOT NULL,
    PNO VARCHAR(10) PRIMARY KEY,
    PLOCATION VARCHAR(255),
    DNO VARCHAR(10)
);

CREATE TABLE WORKS_ON
(
    ESSN CHAR(10) NOT NULL,
    PNO VARCHAR(10) NOT NULL,
    HOURS INT,
    PRIMARY KEY (ESSN, PNO)
);